# Built with Jekyll 3.2.0

# Setup
title:               Essentials of Economics
tagline:             'A Brief Survey of Principles and Policies'
description:         "Essentials of Economics is an accessible survey of economic history, theory, and application in only one hundred pages. It was written by the Catalan polymath Faustino Ballvé in 1956, translated in 1963 by Arthur Goddard with support from the William Volker Fund and the Foundation for Economic Education, and is now in a fresh digital edition from publicly available source texts courtesy of Jack VanDrunen."
url:                 'https://ballve.org'
baseurl:             ''

# About/contact
author:
  name:              Jack VanDrunen
  url:               'https://jackv.co/'

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


